#!/bin/bash -ei
#
# Copyright (C) 2017  Abdel Said <tafnzart@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under the terms of version 3 of the GNU
# General Public License as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#

## 
## NAME:
##     git-dvd - helps manage git-annex repo files on dvds
## 
## USAGE:
##     git-dvd [options] 
## 
## OPTIONS:
##     -h, --help              display this help 
##     -c, --create            create dvds. will prompt to insert a dvd 
##     -s, --startover         mark all files to be added to dvds, this is if you want to create new copies
##         --dead=VALUE        mark dvd with id as dead, this will remove the dvd remote from git annex
## 
## NOTE: this program is not space efficient like what dirsplit or gaffitter do
##
## This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
## warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

set -e

gitdvddir=$( dirname "$(realpath "$(test -L "$0" && readlink "$0" || echo "$0")")" )

. $gitdvddir/thirdparty/easyoptions/bash/easyoptions.sh
. $gitdvddir/lib.sh

if [[ -n "$create"  ]]; then
  gitdvd_create
elif [[ -n "$startover" ]]; then
  gitdvd_startover
elif [[ -n "$dead"   ]]; then
  gitdvd_dead $dead
else
	parse_options "--help"
fi 
